In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# 使用 3 层网络定义 Sequential 模型
model = keras.Sequential(
    [
        layers.Dense(2, activation='relu', name='layer1'),
        layers.Dense(3, activation='relu', name='layer2'),
        layers.Dense(4, name='layer3')
    ]
)
# 对测试样本调用模型
x = tf.ones((3, 3))
y = model(x)

In [3]:
layer1 = layers.Dense(2, activation='relu', name='layer1')
layer2 = layers.Dense(3, activation='relu', name='layer2')
layer3 = layers.Dense(4, name='layer3')

x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [4]:
model = keras.Sequential([
    layers.Dense(2, activation='relu'),
    layers.Dense(3, activation='relu'),
    layers.Dense(4)
])

In [5]:
model.layers

In [6]:
model.pop()
print(len(model.layers))

2


In [7]:
layer = layers.Dense(3)
layer.weights

[]

In [8]:
x = tf.ones((1, 4))
y = layer(x)
layer.weights

[<tf.Variable 'dense_3/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.40250832,  0.3771119 , -0.8667558 ],
        [ 0.12981272, -0.8541893 ,  0.8584156 ],
        [ 0.26037717,  0.5907799 , -0.44195348],
        [ 0.6888095 , -0.70434684,  0.4315971 ]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [9]:
model = keras.Sequential([
    layers.Dense(2, activation='relu'),
    layers.Dense(3, activation='relu'),
    layers.Dense(4)
])  # 此时没有 weights

In [10]:
model.weights  # 会抛出错误

ValueError: Weights for model sequential_2 have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.

In [11]:
model.summary()  # 也会抛出错误

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.

In [12]:
x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))

Number of weights after calling the model: 6


In [18]:
model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (1, 2)                    10        
                                                                 
 dense_8 (Dense)             (1, 3)                    9         
                                                                 
 dense_9 (Dense)             (1, 4)                    16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [13]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, activation='relu'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.layers

In [22]:
model = keras.Sequential()
model.add(layers.Dense(2, activation='relu', input_shape=(4,)))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [15]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB 图片
model.add(layers.Conv2D(32, 5, strides=2, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(3))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 123, 123, 32)      2432      
                                                                 
 conv2d_1 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 40, 40, 32)       0         
 )                                                               
                                                                 
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

In [17]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 123, 123, 32)      2432      
                                                                 
 conv2d_1 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 40, 40, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 38, 38, 32)        9248      
                                                                 
 conv2d_3 (Conv2D)           (None, 36, 36, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 12, 12, 32)       0         
 2D)                                                  

In [18]:
model.add(layers.GlobalMaxPooling2D())
model.add(layers.Dense(10))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 123, 123, 32)      2432      
                                                                 
 conv2d_1 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 40, 40, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 38, 38, 32)        9248      
                                                                 
 conv2d_3 (Conv2D)           (None, 36, 36, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 12, 12, 32)       0         
 2D)                                                  

In [19]:
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

In [20]:
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers]
)
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

In [21]:
features

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
 array([[[[0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          ...,
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ]],
 
         [[0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          [0.1191241 , 0.07604697, 0.        , ..., 0.19091254,
           0.33169365, 0.        ],
          ...,
       

In [22]:
import tensorflow.keras as keras

initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation='relu'),
        layers.Conv2D(32, 3, activation='relu', name='my_intermediate_layer'),
        layers.Conv2D(32, 3, activation='relu')
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name='my_intermediate_layer').output
)
# call feature extractor on test input
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

<tf.Tensor: shape=(1, 121, 121, 32), dtype=float32, numpy=
array([[[[0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         ...,
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ]],

        [[0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         [0.        , 0.39142978, 0.        , ..., 0.42282772,
          0.06077018, 0.0272972 ],
         ...,
         [0.        , 0.39142