In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape

(3,)

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [9]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
X = np.array([[0, 1, 2], [3, 4, 5]])

In [11]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
W1 = np.random.randn(2, 4)

In [14]:
b1 = np.random.randn(4)

In [15]:
x = np.random.randn(10, 2)

In [16]:
h = np.dot(x, W1) + b1

In [17]:
h

array([[ 2.08326493,  0.43995938,  2.00872283,  0.27834079],
       [-2.29693741,  2.953612  ,  2.11786127,  0.97637677],
       [ 0.03358994,  2.47151195,  1.72815442,  0.38665327],
       [ 1.60452073, -0.90114483,  2.64717699,  0.76709342],
       [-0.84920503,  5.57604963,  0.74282869, -0.13581094],
       [-1.55519205,  3.29990792,  1.80006037,  0.66112083],
       [-0.37316595,  1.56202548,  2.18144124,  0.74321376],
       [-2.48786809,  2.01705979,  2.52824149,  1.27383661],
       [-0.10505988,  0.69484969,  2.45134317,  0.88256965],
       [ 1.73743688, -0.20206863,  2.34323009,  0.54799526]])

In [18]:
def sigmoid(x):
    return 1/(x+np.exp(-x))

In [19]:
x = np.random.randn(10, 2)

In [20]:
W1 = np.random.randn(2, 4)

In [21]:
b1 = np.random.randn(4)

In [22]:
W2 = np.random.randn(4, 3)

In [23]:
b2 = np.random.randn(3)