In [2]:
import numpy as np

In [3]:
x = np.array([1])  # 生成向量
x.__class__

numpy.ndarray

In [4]:
x.shape

(1,)

In [5]:
x.ndim  # 表示维度

1

In [6]:
W = np.array([[1, 2, 3],  # 生成矩阵
              [4, 5, 6]])
W.shape

(2, 3)

In [7]:
W.ndim

2

# 逐元素计算

In [8]:
W = np.array([[1, 2, 3],
              [4, 5, 6]])
X = np.array([[0, 1, 2],
              [3, 4, 5]])

In [9]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [10]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

# 广播

In [11]:
A = np.array([[1, 2],
              [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

广播机制可以按下图理解：

![](images/2021-12-07-10-00-24.png)

In [12]:
A = np.array([[1, 2],
              [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

![](images/2021-12-07-10-02-29.png)

# 向量内积和矩阵乘积

向量内积可以表示为：

$x\cdot y = x_1y_1 + x_2y_2+...+x_ny_n$

向量内积是两个向量对应元素的乘积之和。

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)  # 向量，计算内积

32

In [14]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
np.dot(A, B)  # 矩阵，计算矩阵乘积

array([[19, 22],
       [43, 50]])