In [1]:
import tensorflow as tf

In [5]:
print(tf.random.uniform([1]))

tf.Tensor([0.533373], shape=(1,), dtype=float32)


In [6]:
print(tf.random.uniform([1]))

tf.Tensor([0.9002656], shape=(1,), dtype=float32)


In [10]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # A1
print(tf.random.uniform([1]))  # A2

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [11]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # A1
print(tf.random.uniform([1]))  # A2

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)
