In [1]:
import tensorflow as tf

In [2]:
tf.random.uniform(shape=[2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.66330266, 0.6639905 ], dtype=float32)>

In [3]:
tf.random.uniform(shape=[], minval=-1., maxval=0.)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.7678834>

In [4]:
tf.random.uniform(shape=[], minval=5, maxval=10, dtype=tf.int64)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [5]:
tf.random.set_seed(5)
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.random.set_seed(5)
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=0>