In [1]:
import tensorflow as tf

In [2]:
@tf.function
def my_func(x):
    print("Tracing.\n")
    return tf.reduce_sum(x)

In [3]:
x = tf.constant([1, 2, 3])
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [4]:
x = tf.constant([10, 9, 8])
my_func(x)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [5]:
class MyModule(tf.Module):
    def __init__(self, value):
        self.weight = tf.Variable(value)

    @tf.function
    def multiple(self, x):
        return x * self.weight

In [6]:
mod = MyModule(3)
mod.multiple(tf.constant([1, 2, 3]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [7]:
save_path = ".saved"
tf.saved_model.save(mod, save_path)

INFO:tensorflow:Assets written to: .saved\assets


In [9]:
reloaded = tf.saved_model.load(save_path)
reloaded.multiple(tf.constant([1, 2, 3]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>