In [1]:
import tensorflow as tf

In [3]:
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)


In [5]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [6]:
for elem in dataset:
    print(elem.numpy())


8
3
0
8
2
1


In [7]:
it = iter(dataset)
print(next(it).numpy())


8


In [9]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())


22


In [10]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [11]:
dataset2 = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]), tf.random.uniform([4, 100], maxval=100, dtype=tf.int32))
)

dataset2.element_spec


(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [12]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [13]:
# Dataset containing a sparse tensor.
dataset4 = tf.data.Dataset.from_tensors(
    tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
)
dataset4.element_spec


SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [14]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [15]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32)
)
dataset1


<TensorSliceDataset element_spec=TensorSpec(shape=(10,), dtype=tf.int32, name=None)>

In [16]:
tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32)

<tf.Tensor: shape=(4, 10), dtype=int32, numpy=
array([[5, 6, 5, 9, 1, 3, 9, 7, 3, 3],
       [5, 4, 7, 1, 3, 2, 4, 5, 1, 5],
       [5, 6, 1, 1, 2, 6, 8, 9, 4, 5],
       [2, 7, 1, 1, 3, 3, 9, 9, 8, 3]])>

In [17]:
for z in dataset1:
    print(z.numpy())


[3 8 8 4 6 2 3 5 8 5]
[9 3 2 1 5 1 1 2 4 3]
[1 1 4 2 3 2 2 8 8 1]
[5 3 6 4 6 4 1 9 1 1]


In [18]:
dataset2 = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]), tf.random.uniform([4, 100], maxval=100, dtype=tf.int32))
)

dataset2


<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))>

In [19]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

dataset3


<ZipDataset element_spec=(TensorSpec(shape=(10,), dtype=tf.int32, name=None), (TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None)))>

In [20]:
for a, (b, c) in dataset3:
    print("shapes: {a.shape}, {b.shape}, {c.shape}".format(a=a, b=b, c=c))


shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)


In [22]:
train, test = tf.keras.datasets.fashion_mnist.load_data()


Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz: None -- [WinError 10061] No connection could be made because the target machine actively refused it