In [1]:
import tensorflow as tf

print("TensorFlow version: ", tf.__version__)


TensorFlow version:  2.8.0


In [6]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz: None -- [WinError 10061] No connection could be made because the target machine actively refused it

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.27800095, -0.18243524, -0.32130682, -0.0138693 , -0.05083328,
         0.22902712, -0.9523146 ,  0.23277804, -0.18671265, -0.11169323]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.8449951e-22,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.0973950e-22,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.0164495

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2992 - accuracy: 0.9149
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1454 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1091 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0895 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0756 - accuracy: 0.9769


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0717 - accuracy: 0.9775 - 598ms/epoch - 2ms/step


[0.0716572180390358, 0.9775000214576721]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.1194946e-07, 8.5832559e-09, 2.2455561e-05, 1.7866098e-04,
        7.7193300e-11, 8.9379677e-09, 3.6577387e-13, 9.9976498e-01,
        5.7338508e-07, 3.3120705e-05],
       [9.8032831e-07, 5.8613041e-05, 9.9984479e-01, 8.1006190e-05,
        5.5317058e-15, 2.8216211e-06, 5.3067456e-08, 1.3904465e-12,
        1.1677374e-05, 2.6266595e-11],
       [9.9731892e-08, 9.9956959e-01, 5.6959343e-05, 7.9618903e-06,
        6.0599523e-06, 1.4311652e-05, 3.9742954e-05, 1.0153104e-04,
        2.0328345e-04, 4.0050264e-07],
       [9.9984145e-01, 7.8144707e-10, 1.1152010e-05, 3.0016800e-08,
        1.2465817e-06, 5.3614735e-06, 7.8149124e-06, 1.4401690e-05,
        7.1907046e-08, 1.1838077e-04],
       [1.4015175e-06, 3.6343459e-09, 6.8545132e-06, 1.5601460e-09,
        9.9748719e-01, 6.1192473e-08, 9.9746330e-07, 3.1162304e-04,
        5.5570689e-07, 2.1913524e-03]], dtype=float32)>