In [1]:
import tensorflow as tf

In [2]:
start = 3
limit = 18
delta = 3

tf.range(start, limit, delta)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15])>

In [4]:
start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

In [5]:
limit = 5
tf.range(limit)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>