In [1]:
import tensorflow as tf

In [2]:
a = [1, 10, 26.9, 2.8, 166.32, 62.3]
tf.sort(a).numpy()

array([  1.  ,   2.8 ,  10.  ,  26.9 ,  62.3 , 166.32], dtype=float32)

In [3]:
tf.sort(a, direction='DESCENDING').numpy()

array([166.32,  62.3 ,  26.9 ,  10.  ,   2.8 ,   1.  ], dtype=float32)

In [4]:
mat = [[3, 2, 1],
       [2, 1, 3],
       [1, 3, 2]]

In [5]:
tf.sort(mat, axis=-1).numpy()

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
tf.sort(mat, axis=0).numpy()

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])