In [1]:
import tensorflow as tf

In [3]:
x = tf.constant([[1.0, 2.0, 3.0], [4, 5, 6]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [4]:
x.dtype

tf.float32

In [16]:
sum(softmax)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999994>