In [23]:
import tensorflow as tf
import numpy as np

In [24]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])

In [25]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [26]:
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

In [27]:
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

In [28]:
c = tf.matmul(a, b)

In [29]:
c

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>