In [1]:
import tensorflow as tf

In [14]:
softmax = tf.nn.softmax([-1, 0., 1.])

In [15]:
softmax

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09003057, 0.24472848, 0.6652409 ], dtype=float32)>

In [4]:
sum(softmax)

array([b'abc def', b'123 456'], dtype=object)

In [9]:
src_seq, dest_seq = read_file_combined(FILE_NAME, MAX_LENGTH)

src_tokenizer, src_token_seq = tokenize(src_seq)
dest_tokenizer, dest_token_seq = tokenize(dest_seq)

In [10]:
dest_target_token_seq = [x + [STOP_INDEX] for x in dest_token_seq]  # 目标后加上 STOP
dest_input_token_seq = [[STOP_INDEX] + x for x in dest_target_token_seq]

src_input_data = sequence.pad_sequences(src_token_seq)
dest_input_data = sequence.pad_sequences(dest_input_token_seq, padding='post')

dest_target_data = sequence.pad_sequences(dest_target_token_seq, padding='post', maxlen=len(dest_input_data[0]))

In [29]:
rows = len(src_input_data[:, 0])
all_indices = list(range(rows))


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])>