In [1]:
import tensorflow as tf

In [8]:
x = tf.constant([[1., 1.], [2., 2.]])

In [9]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [10]:
tf.reduce_mean(x, 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 1.5], dtype=float32)>

In [11]:
tf.reduce_mean(x, 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [6]:
tf.reduce_sum(x, 1).numpy()

array([3, 3])

In [7]:
tf.reduce_sum(x, 1, keepdims=True).numpy()

array([[3],
       [3]])