In [2]:
import tensorflow as tf


In [2]:
dataset = tf.data.Dataset.range(5)
dataset = dataset.map(lambda x: x**2)
dataset = dataset.cache()
# 第一次迭代数据将使用 `range` 和 `map` 生成数据
list(dataset.as_numpy_iterator())


[0, 1, 4, 9, 16]

In [3]:
list(dataset.as_numpy_iterator())


[0, 1, 4, 9, 16]

In [4]:
dataset = tf.data.Dataset.range(5)
dataset = dataset.cache("/path/to/file")
list(dataset.as_numpy_iterator())
# [0, 1, 2, 3, 4]
dataset = tf.data.Dataset.range(10)
dataset = dataset.cache("/path/to/file")  # Same file!
list(dataset.as_numpy_iterator())
# [0, 1, 2, 3, 4]


NotFoundError: Failed to create a NewWriteableFile: /path/to/file_0.lockfile : The system cannot find the path specified.
; No such process [Op:IteratorGetNext]

In [3]:
layer_a = tf.keras.layers.Dense(1, kernel_initializer=tf.constant_initializer(1.0))
a_out = layer_a(tf.convert_to_tensor([[1.0, 2.0, 3.0]]))
layer_a.get_weights()


[array([[1.],
        [1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32)]

In [4]:
layer_b = tf.keras.layers.Dense(1, kernel_initializer=tf.constant_initializer(2.0))
b_out = layer_b(tf.convert_to_tensor([[10.0, 20.0, 30.0]]))
layer_b.get_weights()


[array([[2.],
        [2.],
        [2.]], dtype=float32),
 array([0.], dtype=float32)]

In [5]:
layer_b.set_weights(layer_a.get_weights())
layer_b.get_weights()


[array([[1.],
        [1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32)]