In [1]:
import torch

print(torch.cuda.is_available())
print(torch.rand(2, 2))

True
tensor([[0.5061, 0.5800],
        [0.8822, 0.0103]])


In [2]:
x = torch.tensor([[0, 0, 1],
                  [1, 1, 1],
                  [0, 0, 0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [3]:
x[0][0] = 5

In [4]:
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [7]:
torch.rand(1).item()

0.14535528421401978

In [8]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [9]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

In [10]:
torch.rand(2, 2).max()

tensor(0.9271)

In [11]:
torch.rand(2, 2).max().item()

0.9215043783187866